:unit_types:
  :cub_scouts:
    :name: 'Cub Scouts'
    :title: 'Pack'
    :short_name: 'CS'
    :sub_unit_name: 'Den'
    :event_types: ['Pack Meeting', 'Camping/Outing', 'Pack Event', 'Den Event', 'Leader Event']
    :ranks: ['Lion', 'Bobcat', 'Tiger', 'Wolf', 'Bear', 'Webelos I', 'Webelos II']
    :scout_leadership_positions: ['Denner']
    :adult_leadership_positions: ['Cubmaster', 'Asst Cubmaster', 'Den Leader', 'Asst Den Leader', 'Tiger Den Leader', 'Asst Tiger Den Leader', 'Webelos Den Leader', 'Asst Webelos Den Leader', 'Committee Chair', 'Committee Member', 'Commissioner', 'Den Chief', 'Round Table Commissioner', 'Chartered Org Rep', 'Webmaster']

  :boy_scouts:
    :name: 'Boy Scouts'
    :title: 'Troop'
    :short_name: 'BS'
    :sub_unit_name: 'Patrol'
    :event_types: ['Troop Meeting', 'Camping/Outing', 'PLC', 'Troop Event', 'Patrol Event', 'Adult Leader Event']
    :ranks: ['Scout', 'Tenderfoot', 'Second Class', 'First Class', 'Star', 'Life', 'Eagle Scout']
    :scout_leadership_positions: ['Senior Patrol Leader', 'Asst Senior Patrol Leader', 'Junior Asst Scoutmaster', 'Troop Guide', 'Scribe', 'Troop Historian', 'Patrol Leader', 'Asst Patrol Leader', 'Quartermaster', 'Librarian', 'Den Chief', 'Chaplain Aide', 'Instructor', 'Webmaster', 'OA Rep', 'Trainer']
    :adult_leadership_positions: ['Scoutmaster', 'Asst Scoutmaster', 'Committee Chair', 'Committee Member', 'Advancement Coord', 'Chartered Org Rep', 'Treasurer', 'Webmaster', 'OA Rep', 'Trainer', 'Secretary', 'Quartermaster']

  :venturing_crew:
    :name: 'Venturing Crew'
    :title: 'Crew'
    :short_name: 'VC'
    :sub_unit_name: 'Team'
    :event_types: ['Crew Meeting', 'Camping/Outing', 'Crew Event', 'Adult Leader Event']
    :ranks: ['Bronze Award', 'Silver Award', 'Gold Award', 'Qwest Award', 'TRUST Award', 'Ranger Award']
    :scout_leadership_positions: []
    :adult_leadership_positions: []

  :girl_scouts:
    :name: 'Girl Scouts'
    :title: 'Troop'
    :short_name: 'GS'
    :sub_unit_name: 'Patrol'
    :event_types: ['Troop Event', 'Patrol Event', 'Adult Leader Event']
    :ranks: ['Daisy', 'Brownie', 'Junior', 'Cadette', 'Senior', 'Ambasador']
    :scout_leadership_positions: []
    :adult_leadership_positions: []

  :order_of_the_arrow:
    :name: 'Order of the Arrow'
    :title: 'Troop'
    :short_name: 'OA'
    :sub_unit_name: 'Patrol'
    :event_types: ['Lodge Meeting', 'Camping/Outing', 'Lodge Event', 'Patrol Event', 'Adult Leader Event']
    :ranks: ['Ordeal', 'Brotherhood', 'Vigil Honor']
    :scout_leadership_positions: []
    :adult_leadership_positions: []
